# This is the configuration used to check the rubocop source code.

#inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Documentation:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - have_
