scss_files: 'app/assets/stylesheets/'

exclude:
  - 'app/assets/stylesheets/material_ui/theme.scss'

linters:
  ImportantRule:
    enabled: false
  IdSelector:
    enabled: false
  SelectorDepth:
    enabled: false
  QualifyingElement:
    enabled: false
