scss_files: 'app/assets/stylesheets/'

exclude:
  - 'app/assets/stylesheets/app/theme.scss'
  - 'app/assets/stylesheets/public/*.min.scss'
  - 'app/assets/stylesheets/public/datetimepicker.scss'

linters:
  ImportantRule:
    enabled: false
  IdSelector:
    enabled: false
  SelectorDepth:
    enabled: false
  QualifyingElement:
    enabled: false
