scss_files: 'app/assets/stylesheets/'
exclude: 'app/assets/stylesheets/app/theme.scss'

linters:
  ImportantRule:
    enabled: false
  IdSelector:
    enabled: false
  SelectorDepth:
    enabled: false
  QualifyingElement:
    enabled: false
